# Generated by Django 6.0.5 on 2026-05-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
